name: ${project.artifactId}
main: work.xeltica.craft.hub.Main
version: ${project.version}
api-version: 1.16
commands:
  hub:
    aliases: [ hub ]
    description: Go to the hub
    usage: Run /hub help